version: 2
jobs:
  build:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v2.0.5
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add storageos https://github.com/storageos/charts
            git fetch storageos master
            chart_test.sh --config test/.testenv --no-install

  e2e:
    machine: true
    steps:
      - run: sudo apt -y update
      - run: sudo apt -y install linux-image-extra-$(uname -r)
      - run: sudo mount --make-rshared /sys
      - run: docker run --name enable_lio --privileged --rm --cap-add=SYS_ADMIN -v /lib/modules:/lib/modules -v /sys:/sys:rshared storageos/init:0.1

  deploy:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v2.0.5
    steps:
      - checkout
      - run: test/repo-sync.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - e2e
      - deploy:
          requires:
            - build
            - e2e
          filters:
            branches:
              only: master
