{{- if .Values.podSecurityPolicy.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "storageoscluster-operator.fullname" . }}-psp-user
  labels:
    app: {{ template "storageoscluster-operator.name" . }}
    chart: {{ template "storageoscluster-operator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ template "storageoscluster-operator.fullname" . }}-psp

{{- end }}
