{{- if .Values.podSecurityPolicy.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "storageoscluster-operator.fullname" . }}-psp-user
  labels:
    app: {{ template "storageoscluster-operator.name" . }}
    chart: {{ template "storageoscluster-operator.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "storageoscluster-operator.fullname" . }}-psp-user
subjects:
  - kind: ServiceAccount
    name: {{ template "storageoscluster-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}
